# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mike Connor
email: mike@mikeconnor.tech
description: > # this means to ignore newlines until "baseurl:"
  Front-end Developer based in New Orleans
baseurl: "" # the subpath of your site, e.g. /blog
url: http://mconnor.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mikeconnor504
github_username:  mconnor
show_downloads: false
github.is_project_page: false

# Build settings
markdown: kramdown
kramdown:
  auto_ids:     true
encoding:       UTF-8
theme: jekyll-theme-architect
plugins_dir:
  - jekyll-seo-tag
gems:
  - jekyll-feed
  - jekyll-octicons
exclude:
  - Gemfile
  - Gemfile.lock
  - .git/
  - package.json
  - package-lock.json
  - node_modules
